site:
    title: Example.nl prototype
    language: nl
    pretty_urls: false
    default_format: 0
    template_engine: twig
    enable_gzip: true
    cache_time: 0
    display_errors: true
    enable_debug_info: true
    timezone: Europe/Amsterdam

baker:
    skip_patterns:
        - /^index.php/
        - /static\/\.sass-cache/
        - /node_modules/

STATIC_URL: static/

